name: eschool
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter & Material
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get: ^4.6.5

  # UI & animations
  flutter_svg: ^2.1.1
  google_fonts: ^6.1.0
  dotted_border: ^2.1.0   # fixed version for compatibility
  table_calendar: ^3.0.11
  lottie: ^3.3.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.2
  carousel_slider: ^5.1.0
  fl_chart: ^1.0.0
  pinch_zoom: ^2.0.1
  flutter_tex: ^5.1.10
  readmore: ^3.0.0
  flutter_widget_from_html: ^0.17.0
  youtube_player_flutter: ^9.1.2
  video_player: ^2.8.2  # added missing dependency

  # Networking & storage
  dio: ^5.3.1
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.12
  web_socket_channel: ^3.0.3
  file_picker: ^10.3.1
  permission_handler: ^12.0.1
  open_filex: ^4.3.2
  image_picker: ^1.1.2
  wakelock_plus: ^1.2.10
  timeago: ^3.5.0
  intl: ^0.20.2  # added missing dependency

  # Firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  awesome_notifications: ^0.10.1
  flutter_stripe: ^10.1.1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/languages/
    - google_fonts/
